site_name: Time Tracker
repo_url: https://github.com/foe-eof/time-tracker-docs
edit_uri: blob/master/docs/
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

strict: true
